### ISSUE TITLE
Brak obrazka w sekcji dodatki.

### ISSUE THREAD

**Issue by 1maniac-f** [1maniac/pizzeriaDV#9]
Cześć! Zauważyłem, że w sekcji z dodatkami brakuje obrazka! Zdaję się, że trzeba to poprawić.

**Comment by 1maniac** [comment]
Commit 8398f4f naprawia ten błąd.

**Comment by 1maniac** [comment]
8398f4f fixes #9

**Comment by 1maniac** [comment]
Fixed
